deployment:
  svc: true 
  bff: true
  ui: true

product:
  info:
    data:
      description: "Manage Documents"
      imageUrl: ""
      iconName: file
      displayName: "OneCX Document"
      basePath: /document
      provider: "OneCX Team"
      classifications: [ "Administration" ]